$script = <<SCRIPT
#Instala o Apache , o PHP e o SQL
sudo yum install -y httpd
sudo yum install mariadb-server mariadb -y
sudo yum install php php-mysql -y
sudo echo "<?php phpinfo(); ?>" > /var/www/html/info.php

#instalando o zabbix
sudo yum -y update
sudo yum clean all	
sudo yum -y install vim htop tcpdump telnet
sudo yum -y install httpd php php-pdo php-mysql mariadb-server
sudo systemctl start httpd.service
sudo systemctl enable httpd.service
sudo systemctl enable mariadb.service
sudo systemctl start mariadb.service
sudo rpm -ivh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
sudo yum install -y zabbix-server-mysql zabbix-web-mysql zabbix-proxy-mysql zabbix-agent
sudo zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -ppassword zabbix
sudo yum -y install zabbix-agent
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.provision "shell", inline: $script
   
end
